// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ozoncp/ocp-response-api/internal/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/ozoncp/ocp-response-api/internal/models"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// AddResponses mocks base method.
func (m *MockRepo) AddResponses(arg0 []models.Response) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResponses", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddResponses indicates an expected call of AddResponses.
func (mr *MockRepoMockRecorder) AddResponses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResponses", reflect.TypeOf((*MockRepo)(nil).AddResponses), arg0)
}

// DescribeResponse mocks base method.
func (m *MockRepo) DescribeResponse(arg0 uint64) (*models.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeResponse", arg0)
	ret0, _ := ret[0].(*models.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeResponse indicates an expected call of DescribeResponse.
func (mr *MockRepoMockRecorder) DescribeResponse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeResponse", reflect.TypeOf((*MockRepo)(nil).DescribeResponse), arg0)
}

// ListResponses mocks base method.
func (m *MockRepo) ListResponses(arg0, arg1 uint64) ([]models.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListResponses", arg0, arg1)
	ret0, _ := ret[0].([]models.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListResponses indicates an expected call of ListResponses.
func (mr *MockRepoMockRecorder) ListResponses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListResponses", reflect.TypeOf((*MockRepo)(nil).ListResponses), arg0, arg1)
}

// RemoveResponse mocks base method.
func (m *MockRepo) RemoveResponse(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveResponse", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveResponse indicates an expected call of RemoveResponse.
func (mr *MockRepoMockRecorder) RemoveResponse(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveResponse", reflect.TypeOf((*MockRepo)(nil).RemoveResponse), arg0)
}
